# Generated by Django 5.1.5 on 2025-02-07 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_table'),
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('etapa', models.IntegerField(blank=True, null=True)),
                ('gera_pendencia', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'service_order_stages',
                'ordering': ['etapa'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_os', models.IntegerField(blank=True, null=True)),
                ('numero_os', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('cancelado', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', max_length=1)),
                ('faturado', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', max_length=1)),
                ('pendencia', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', max_length=1)),
                ('servico_id', models.IntegerField(blank=True, null=True)),
                ('servico_item_id', models.IntegerField(blank=True, null=True)),
                ('servico_descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('servico_quantidade', models.IntegerField(blank=True, null=True)),
                ('servico_valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('servico_valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='clients.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='companies.company')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='projects.project')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_order.servicestages')),
            ],
            options={
                'verbose_name': 'Ordem de serviço',
                'verbose_name_plural': 'Ordens de serviço',
                'db_table': 'service_order',
                'ordering': ['name'],
            },
        ),
    ]
