# Generated by Django 5.1.5 on 2025-02-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0002_serviceorder_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='temp_field',
        ),
    ]
