# Generated by Django 5.1.5 on 2025-02-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0004_servicestages_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='client_id',
            new_name='client',
        ),
    ]
