# Generated by Django 5.1.5 on 2025-02-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('etapa', models.IntegerField(blank=True, null=True)),
                ('gera_pendencia', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'purchase_order_stages',
                'ordering': ['etapa'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_pedido', models.IntegerField(blank=True, null=True)),
                ('numero_pedido', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('cancelado', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', max_length=1)),
                ('faturado', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', max_length=1)),
                ('pendencia', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', max_length=1)),
                ('produto_codigo', models.CharField(blank=True, max_length=500, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('product_descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('product_quantidade', models.IntegerField(blank=True, null=True)),
                ('product_valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clients.client')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='projects.project')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_order.purchasestages')),
            ],
            options={
                'verbose_name': 'Pedido de compra',
                'verbose_name_plural': 'Pedidos de compra',
                'db_table': 'purchase_order',
                'ordering': ['name'],
            },
        ),
    ]
