# Generated by Django 5.1.5 on 2025-02-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('codigo_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(blank=True, max_length=500, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clients',
            },
        ),
    ]
