# Generated by Django 5.1.5 on 2025-02-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
    ]
